export const ADD_PUPPY = 'ADD_PUPPY';

export const GET_PUPPIES = 'GET_PUPPIES';

export const DELETE_PUPPY = 'DELETE_PUPPY';

export const ADOPT_PUPPY = 'ADOPT_PUPPY';

export const PUPPIES_GET_REQUEST = 'PUPPIES_GET_REQUEST';

export const PUPPIES_GET_SUCCESS = 'PUPPIES_GET_SUCCESS';