export const ADD_PUPPY = 'ADD_PUPPY';

export const DELETE_PUPPY_REQUEST = 'DELETE_PUPPY_REQUEST';
export const DELETE_PUPPY_SUCCESS = 'DELETE_PUPPY_SUCCESS';

export const ADOPT_PUPPY_REQUEST = 'ADOPT_PUPPY_REQUEST';
export const ADOPT_PUPPY_SUCCESS = 'ADOPT_PUPPY_SUCCESS';

export const PUPPIES_GET_REQUEST = 'PUPPIES_GET_REQUEST';
export const PUPPIES_GET_SUCCESS = 'PUPPIES_GET_SUCCESS';