export const ADD_PUPPY = 'ADD_PUPPY';

export const DELETE_PUPPY = 'DELETE_PUPPY';

export const ADOPT_PUPPY_REQUEST = 'ADOPT_PUPPY_REQUEST';

export const ADOPT_PUPPY_SUCCESS = 'ADOPT_PUPPY_SUCCESS';

export const PUPPIES_GET_REQUEST = 'PUPPIES_GET_REQUEST';

export const PUPPIES_GET_SUCCESS = 'PUPPIES_GET_SUCCESS';